# Client configuration
aerospike_db_host: localhost
aerospike_db_port: 3000
aerospike_license_type: enterprise
aerospike_admin_namespace: cf_admin
aerospike_admin_user: cf_admin
aerospike_admin_password: cf_admin
aerospike_license_user: none
aerospike_license_password: none

# Catalog configuration
aerospike_service_id: aerospike-service-broker
aerospike_service_name: aerospike
aerospike_service_description: Aerospike Enterprise Edition Managed Service
